site_name: Warehouse Management API
site_description: Documentation for the Warehouse Management API
site_author: Your Name
repo_url: https://github.com/yourusername/go-warehouse-management

nav:
  - Home: index.md
  - API Reference:
    - Authentication: api/auth.md
    - Items: api/items.md
    - Locations: api/locations.md
    - Issues: api/issues.md
    - Reports: api/reports.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search